(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: 160x11TB.drl_edit_mill_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Tuesday, 25 November 2025 at 13:52)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)

(TOOL DIAMETER: 2.0 mm)
(Feedrate_XY: 120.0 mm/min)
(Feedrate_Z: 60.0 mm/min)
(Feedrate rapids 1500.0 mm/min)

(Z_Cut: 0.0 mm)
(DepthPerCut: 0.10000000000000014 mm <=>0 passes)
(Z_Move: 2.0 mm)
(Z Start: None mm)
(Z End: 30.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Preprocessor Geometry: default)

(X range:    3.9400 ...   71.7800  mm)
(Y range:  -59.5600 ...   -3.3100  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G94

G01 F120.00

M5
G00 Z30.0000
G00 X0.0000 Y0.0000
T1
M6    
(MSG, Change to Tool Dia = 2.0000)
M0
G00 Z30.0000

M03 S10000.0
G01 F120.00
G00 Z2.0000
G00 Z2.0000
G00 Z2.0000
M05
G00 Z2.0000
G00 Z30.00


